### ISSUE TITLE
Wrong repository URL for Hecke

### ISSUE THREAD

**Issue by fingolfin** [rbehrends/oscar-ci#1]
https://github.com/rbehrends/oscar-ci/blob/5950b15860e89313ecf35b3180a4fa19fe5e8964/Jenkinsfile#L53

**Comment by fingolfin** [comment]
Maybe https://github.com/thofma/Hecke.jl is the correct one?

**Comment by rbehrends** [comment]
Fixed in https://github.com/rbehrends/oscar-ci/commit/cb815295df8346775ee9a50880223b781dcca476.
