### ISSUE TITLE
Wrong Nemo.jl URL

### ISSUE THREAD

**Issue by fingolfin** [rbehrends/oscar-ci#3]
https://github.com/rbehrends/oscar-ci/blob/5950b15860e89313ecf35b3180a4fa19fe5e8964/Jenkinsfile#L49

Should be https://github.com/Nemocas/Nemo.jl

**Comment by rbehrends** [comment]
Fixed in https://github.com/rbehrends/oscar-ci/commit/cb815295df8346775ee9a50880223b781dcca476.
